language: cpp

cache:
  - apt: true

matrix:
  include:

    - os: linux
      sudo: true
      compiler: gcc
      install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install zlib1g-dev
          #- sudo apt-get install g++-4.8 zlib1g-dev
          # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
          # - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90

    - os: osx
      compiler: clang-3.7

script:
  - make test

